version: '2'
services:
    gamesales2-app:
        image: gamesales2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gamesales2-postgresql:5432/GameSales2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gamesales2-postgresql:
        extends:
            file: postgresql.yml
            service: gamesales2-postgresql
